version: "3.9"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5678:5678"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"