[project]
name = "2025gpnprint2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "build>=1.3.0",
    "compose>=1.6.2",
    "docker>=7.1.0",
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "pyodbc>=5.2.0",
]
